---
abstract: 'Load config files, reload when files changed.'
author:
  - 'Jakob Voß'
build_requires:
  Data::Dumper: 0
  File::Basename: 0
  File::Temp: 0
  Test::More: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300031, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Reload
requires:
  Config::ZOMG: 0
  Digest::MD5: 0
  Exporter: 0
  Moo: 0
  Sub::Quote: 0
  Try::Tiny: 0
  parent: 0
  perl: v5.10.0
  strict: 0
version: 0.2
